//post resource
GET http://localhost:8080/post/ping



//answer resource
###
GET http://localhost:8080/answer/ping


//comment resource
###
GET http://localhost:8080/comment/ping


//user resource
###
POST http://localhost:8080/user/login
###
DELETE http://localhost:8080/user/logout
###



//triger exception  login api only support POST
GET http://localhost:8080/user/login
###
//triger exception  post/ping api only support GET
POST http://localhost:8080/post/ping
###


//system manager
GET http://localhost:8080/ping
###
GET http://localhost:8080/shutdown
###