//post resource
GET http://localhost:8080/post/ping



//answer resource
###
GET http://localhost:8080/answer/ping


//comment resource
###
GET http://localhost:8080/comment/ping


//user resource  notice:请求体与请求头加个空行隔开，这样http client tool才能正确解析
###
POST http://localhost:8080/user/login
Content-Type: application/json

{
"authType":1,
"username":"1A中文",
"password":"encryedpass"
}
###
DELETE http://localhost:8080/user/logout
###



//triger exception  login api only support POST
GET http://localhost:8080/user/login
###
//triger exception  post/ping api only support GET
POST http://localhost:8080/post/ping
###


//system manager
GET http://localhost:8080/ping
###
GET http://localhost:8080/shutdown
###