#profiles.active is a placeholder defined in pom.xml ,maven resources plugin will replace it where building, see filtering
spring:
  profiles:
    active: @profiles.active@

author:
  name: tli2

#各个环境的通用配置可以放在这个文件

#https://stackoverflow.com/a/46775070 fix 关闭应用时，EsAppender#stop没有触发的问题
logging:
  register-shutdown-hook: true

#todo 把mapper.xml文件和dao放在一起，配置maven插件，打包的时候自动把mapper文件copy一份到resource/mybatis/mapper目录下
#mapper.xml文件在类路径下的位置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
