//post resource
GET http://localhost:8080/post/ping

###
GET  http://localhost:8080/post

###
GET http://localhost:8080/post?state=ACTIVE,ARCHIVED

###
GET http://localhost:8080/post?state=ACTIVE,ARCHIVED&limit=1

###
GET http://localhost:8080/post?state=ACTIVE,ARCHIVED&limit=1&offset=1



//answer resource
###
GET http://localhost:8080/answer/ping


//comment resource
###
GET http://localhost:8080/comment/ping


//user resource  notice:请求体与请求头加个空行隔开，这样http client tool才能正确解析
###
POST http://localhost:8080/user/login
Content-Type: application/json

{
"authType":1,
"username":"A1",
"password":"979d697cc06f903246c2d2d70e07d030--md5(password_for_hfvj)"
}
###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "authType":1,
  "username":"A2",
  "password":"af0c402fa7cbb47e212d20a068f558ce--md5(password_for_upup?)"
}
###
DELETE http://localhost:8080/user/logout
pser: 8f6d676e8e8dc10640d3cda7a313f64a5b057684e8f142bda002a9b495129e9e221930a69bd74f540c7998f2a5228aa2
###



//triger exception  login api only support POST
GET http://localhost:8080/user/login
###
//triger exception  post/ping api only support GET
POST http://localhost:8080/post/ping
###


//system manager
GET http://localhost:8080/ping
###
GET http://localhost:8080/parse?pserId=332cc40c41b88885d27ffd3aa89aa5a13eeb2203750f0fe32ed4dca96b695cd49da610348b9116a70c7998f2a5228aa2
###
GET http://localhost:8080/shutdown
###